apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: qlab-apiserver
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: qlab-config