apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmanager
  template:
    metadata:
      labels:
        app: dbmanager
    spec:
      serviceAccountName: dbmanager-account
      containers:
      - name: dbmanager
        image: hoon317/qlab-dbmanager
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: qlab-config
        env:
        - name: QUERY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qlab-secret
              key: querydb-password
