apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmanager
  template:
    metadata:
      labels:
        app: dbmanager
    spec:
      serviceAccountName: dbmanager-account
      containers:
      - name: dbmanager
        image: qlab-dbmanager:latest
        ports:
        - containerPort: 3000
