apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: apiserver
        image: choco181/qlab-apiserver:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: qlab-config
          - secretRef:
              name: qlab-secret
      nodeSelector:
        ncloud.com/nks-nodepool: server-nodepool
  selector:
    matchLabels:
      app: apiserver