apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmanager-deployment
spec:
  template:
    spec:
      containers:
        - name: dbmanager
          image: choco181/qlab-dbmanager:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qlab-config
            - secretRef:
                name: qlab-secret
      nodeSelector:
        ncloud.com/nks-nodepool: nodepool-server
  selector:
    matchLabels:
      app: dbmanager