apiVersion: apps/v1
kind: Deployment
metadata:
  name: querydb-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: querydb
      role: master
  template:
    metadata:
      labels:
        app: querydb
        role: master
    spec:
      containers:
        - name: querydb
          image: mysql:8.3
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: querydb-data
              mountPath: /var/lib/mysql
          args:
            - "--local-infile=1"
            - "--server-id=1"
            - "--log-bin=mysql-bin"
            - "--binlog-format=ROW"
            - "--gtid-mode=ON"
            - "--enforce-gtid-consistency=ON"