apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: querydb
spec:
  serviceName: querydb
  replicas: 2
  selector:
    matchLabels:
      app: querydb
  template:
    metadata:
      labels:
        app: querydb
    spec:
      containers:
        - name: querydb
          image: mysql:8.3
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: querydb-data
              mountPath: /var/lib/mysql
          args:
            - "--local-infile=1"
  volumeClaimTemplates:
    - metadata:
        name: querydb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi