resources:
  - ../../../base/queryDB
  - replica-deployment.yaml
  - replica-hpa.yaml
  - pvc.yaml

patches:
  - path: primary-deployment.yaml
    target:
      kind: Deployment
      name: querydb-master