apiVersion: apps/v1
kind: Deployment
metadata:
  name: querydb-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: querydb
      role: master
  template:
    metadata:
      labels:
        app: querydb
        role: master
    spec:
      nodeSelector:
        ncloud.com/nks-nodepool: nodepool-master
      containers:
        - name: querydb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qlab-secret
                  key: root-password
          envFrom:
            - configMapRef:
                name: qlab-config
            - secretRef:
                name: qlab-secret
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: querydb-data
          persistentVolumeClaim:
            claimName: querydb-master-pvc